version: 2
updates:
  - package-ecosystem: npm
    directory: /
    allow:
      - dependency-name: "@openai/codex-sdk"
      - dependency-name: "@openai/codex"
    schedule:
      interval: daily
    open-pull-requests-limit: 2

  - package-ecosystem: npm
    directory: /
    ignore:
      - dependency-name: "@openai/codex-sdk"
      - dependency-name: "@openai/codex"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
